spring.application.name=search
# Your database connection
spring.mongodb.uri=${MONGODB_URI}
spring.ai.vectorstore.mongodb.initialize-schema=true

# Your Ollama connection
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

youtube.api.key=${YOUTUBE_API}
youtube.api.base-url=https://www.googleapis.com/youtube/v3/search