package com.youtube.search.controller;

import com.youtube.search.dto.ExpandedIntent;
import com.youtube.search.dto.YouTubeItem;
import com.youtube.search.service.*;
import org.springframework.ai.document.Document;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@RestController
@RequestMapping("/api")
@CrossOrigin(origins = "http://localhost:5173")
public class AgentController {

    @Autowired
    private IntentAgentService intentAgentService;

    @Autowired
    private YoutubeHarvestService youtubeHarvestService; // Added for Phase 2
    @Autowired
    private  VectorIngestionService vectorIngestionService;
    @Autowired
    private SemanticSearchService semanticSearchService;
    @Autowired
    private VideoRankingService videoRankingService;
    @GetMapping("/v1/search/expand")
    public ExpandedIntent expandQuery(@RequestParam String query) {
        return intentAgentService.broadenSearchIntent(query);
    }

    @GetMapping("/v1/search/discover")
    public Map<String, Object> discoverContent(@RequestParam String query) {
        // 1. Call your Local Agent to get the structured queries
        ExpandedIntent intent = intentAgentService.broadenSearchIntent(query);

        // 2. Safely grab both queries from the list generated by the LLM
        String queryOne = intent.consolidatedQueries().get(0);
        String queryTwo = intent.consolidatedQueries().get(1);

        // 3. Harvest live data from YouTube for both tracks
        List<YouTubeItem> resultsOne = youtubeHarvestService.fetchVideosForQuery(queryOne);
        List<YouTubeItem> resultsTwo = youtubeHarvestService.fetchVideosForQuery(queryTwo);

        // 4. Combine and eliminate any overlapping duplicate items
        List<YouTubeItem> unifiedResults = Stream.concat(resultsOne.stream(), resultsTwo.stream())
                .distinct()
                .collect(Collectors.toList());

        // 5. Structure the final response payload
//        Map<String, Object> finalPayload = new HashMap<>();
//        finalPayload.put("searchAnalysis", intent);
//        finalPayload.put("harvestedVideos", unifiedResults);

        vectorIngestionService.ingestVideos(unifiedResults);
        Map<String, Object> finalPayload = new HashMap<>();
        finalPayload.put("searchAnalysis", intent);
        finalPayload.put("harvestedVideos", unifiedResults);
        finalPayload.put("message", "Successfully fetched and vectorized " + unifiedResults.size() + " videos.");
        return finalPayload;
    }

    @GetMapping("/v1/search/semantic")
    public Map<String, Object> semanticSearch(@RequestParam String query) {

        // 1. Fetch raw candidates from MongoDB Atlas vector index
        List<Document> rawMatches = semanticSearchService.findSimilarVideos(query);

        // 2. Pass candidates to the LLM to calculate match percentages and rank them
        List<Document> aiRankedMatches = videoRankingService.rankVideos(query, rawMatches);

        // 3. Construct payload
        Map<String, Object> response = new HashMap<>();
        response.put("userQuery", query);
        response.put("totalMatchesFound", aiRankedMatches.size());

        // Inside semanticSearch method in AgentController.java
        List<Map<String, Object>> formattedResults = aiRankedMatches.stream()
                .map(doc -> {
                    Map<String, Object> resultInfo = new HashMap<>();
                    resultInfo.put("videoId", doc.getMetadata().get("videoId"));
                    resultInfo.put("channel", doc.getMetadata().get("channelTitle"));
                    resultInfo.put("content", doc.getText());

                    // CRITICAL FIX: Change default from 80 to 0 so you see real failures
                    int score = ((Number) doc.getMetadata().getOrDefault("vibeMatchScore", 0)).intValue();
                    resultInfo.put("vibeMatchScore", score);
                    return resultInfo;
                })
                // Optional: Filter out videos that the AI ranks as completely irrelevant (below 15%)
                .filter(video -> ((Integer) video.get("vibeMatchScore")) > 15)
                .collect(Collectors.toList());

        response.put("results", formattedResults);
        return response;
    }
}